package com.finapp.platform.correlation;

import com.finapp.sharedkernel.id.IdGenerator;
import java.util.Objects;

/**
 * The identifier that ties one business flow together, end to end.
 *
 * <p>A correlation identifier is stable for the whole life of a flow: the same value appears on
 * the inbound request, every log line it produces, every event it emits, every provider call it
 * makes, every posting it causes and every reconciliation record that later refers to it. That
 * is what {@code CLAUDE.md} §Events means by traceability across customer → request → domain →
 * provider → ledger → settlement → reconciliation, and it is the difference between answering
 * "what happened to this payment" in one query and reconstructing it from timestamps.
 *
 * <p><strong>Why this is a validated token and not a UUID.</strong> A correlation identifier may
 * be <em>accepted</em> from the caller, so that a client, a gateway or an upstream service can
 * tie its own trace to ours. That means its value is untrusted input, and it means we cannot
 * require it to be a UUID — the caller's tracing system has its own format. So the type accepts
 * any opaque token within a bounded charset, and generates a UUIDv7 when the caller supplies
 * none.
 *
 * <p><strong>Why the charset is restricted.</strong> This value is written into log lines. A
 * value containing a newline can forge log entries — a fabricated "authorization granted" line
 * attributed to the platform's own logger — and one containing control characters can corrupt a
 * log pipeline that parses them. Truncation bounds the other direction: an unbounded header
 * becomes an unbounded log line and an unbounded database column. Both are rejected rather than
 * sanitised, because silently rewriting a caller's identifier breaks the tie to their trace
 * while looking like it worked.
 */
public final class CorrelationId {

    /**
     * Long enough for a UUID, a W3C trace parent, or a provider's own reference; short enough
     * that it cannot be used to inflate every log line and audit row in a flow.
     */
    public static final int MAX_LENGTH = 128;

    private final String value;

    private CorrelationId(String value) {
        this.value = value;
    }

    /**
     * Accepts a caller-supplied identifier.
     *
     * @throws NullPointerException if {@code value} is null
     * @throws IllegalArgumentException if it is blank, too long, or contains anything outside
     *     the safe token charset
     */
    public static CorrelationId of(String value) {
        return new CorrelationId(CorrelationTokens.validate(value, MAX_LENGTH, "correlation id"));
    }

    /**
     * Mints a new identifier for a flow that arrived without one.
     *
     * <p>UUIDv7, so correlation identifiers generated by the platform sort by time — the same
     * reason ADR-0013 chose it for aggregate identifiers, and useful for the same reason when
     * scanning a log.
     */
    public static CorrelationId generate(IdGenerator generator) {
        Objects.requireNonNull(generator, "generator must not be null");
        return new CorrelationId(generator.next().toString());
    }

    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        return o instanceof CorrelationId other && value.equals(other.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
