-- The transfer and its lifecycle history (P4-TSK-004, ADR-0044).
--
-- THE JUDGEMENT AND ITS RECORD, NEVER THE MONEY. There is an amount here because the amount is
-- what was commanded; the money that moved is a ledger posting this row holds the EVIDENCE
-- identifier of (journal_entry_id), commanded through the ledger and written by nothing in this
-- schema (INV-LED-04, ADR-0043).
--
-- EVERY GENERATED LIST BELOW HAS ONE DEFINITION. The status CHECK comes from
-- TransferStatus.sqlValueList(), the reason CHECK from FailureReason.sqlValueList(), the
-- monetary shape from MoneyColumns.ColumnNames.ddl(), and the transition trigger's edge
-- conditions from TransferStatus.permittedTransitions(). TransferMigrationTest fails the build
-- if this file and the code disagree (the P0-TSK-022 pattern).
--
-- NO CROSS-SCHEMA FOREIGN KEYS, DELIBERATELY. customer_id references party.customer,
-- source/destination reference ledger.ledger_account, and the entry ids reference
-- ledger.journal_entry - all by value (ADR-0029's rule): a cross-schema FK is coupling Gradle
-- and ArchUnit cannot see. What guarantees they exist is the execution transaction, which
-- resolves every one of them from authoritative state (P4-TSK-005).
--
-- INITIATED IS NEVER DURABLY OBSERVED (ADR-0044): the row commits carrying its outcome, and the
-- grants below FORCE that design - a FAILED outcome cannot arrive by UPDATE because
-- failure_reason is not in the granted column set, and a COMPLETED one cannot gain its entry.
-- The only UPDATE this table will ever legitimately see is the reversal.

CREATE TABLE transfers.transfer (
    -- UUIDv7, minted by the application (ADR-0013) - and the value that travels in the journal
    -- entry's reference when the transfer posts, so movement and evidence join by identifier in
    -- both directions (PHASE_4_PLAN.md section 12).
    id                     uuid        PRIMARY KEY,

    -- The customer whose movement this is - the ownership predicate's column (P4-TSK-008).
    customer_id            uuid        NOT NULL,

    -- The two ledger accounts, by value. Equality is judged below.
    source_account_id      uuid        NOT NULL,
    destination_account_id uuid        NOT NULL,

    -- The ADR-0003 three-column monetary shape, generated by MoneyColumns.ColumnNames.ddl()
    -- and pinned verbatim by TransferMigrationTest so the shape cannot drift per table.
    amount_minor BIGINT NOT NULL, currency CHAR(3) NOT NULL, scale SMALLINT NOT NULL, CHECK (currency ~ '^[A-Z]{3}$'), CHECK (scale BETWEEN 0 AND 9),

    -- A zero amount moves nothing; a negative one is a credit wearing a debit's clothes
    -- (the V004 journal_line rule, and the aggregate's own constructor invariant).
    CONSTRAINT transfer_amount_is_positive
        CHECK (amount_minor > 0),

    -- The caller's memo. Free text a person writes (RESTRICTED-PII at the register); the
    -- boundary DTO restates this bound where the caller is told about it (P4-TSK-008).
    reference              text
        CONSTRAINT transfer_reference_is_bounded
            CHECK (length(reference) <= 200),

    -- Generated from TransferStatus.sqlValueList(). The machine lives on the enum and in the
    -- aggregate (INV-LIFE-02); this CHECK bounds what any writer can store, and the trigger
    -- below bounds how a stored value may move.
    status                 text        NOT NULL
        CONSTRAINT transfer_status_is_known
            CHECK (status IN ('INITIATED', 'COMPLETED', 'FAILED', 'REVERSED')),

    -- Generated from FailureReason.sqlValueList().
    failure_reason         text
        CONSTRAINT transfer_failure_reason_is_known
            CHECK (failure_reason IN ('INSUFFICIENT_FUNDS', 'SOURCE_NOT_POSTABLE', 'DESTINATION_NOT_POSTABLE', 'CURRENCY_MISMATCH', 'SELF_TRANSFER')),

    -- The reason exists exactly when FAILED: a refusal without its reason is a support ticket
    -- the platform caused (ADR-0044), and a reason on anything else is incoherent. The
    -- aggregate's constructor rule at DB-CONSTRAINT rank, for the writer that never ran it.
    CONSTRAINT transfer_reason_arrives_exactly_when_failed
        CHECK ((status = 'FAILED') = (failure_reason IS NOT NULL)),

    -- The evidence exists exactly when money moved - and REVERSED keeps the original entry,
    -- because the reversal is a NEW entry referencing it (INV-REV-01), never its removal.
    -- UNIQUE: one transfer per posted entry, whichever instance wrote it.
    journal_entry_id       uuid        UNIQUE,
    CONSTRAINT transfer_entry_arrives_exactly_when_money_moved
        CHECK ((status IN ('COMPLETED', 'REVERSED')) = (journal_entry_id IS NOT NULL)),

    -- The reversal triple arrives together, exactly when REVERSED - a reversal without its
    -- actor or instant is an unattributable correction (INV-AUD-01's reasoning at the row).
    reversal_entry_id      uuid,
    reversed_by            uuid,
    reversed_at            timestamptz,
    CONSTRAINT transfer_reversal_columns_arrive_together
        CHECK (((status = 'REVERSED') = (reversal_entry_id IS NOT NULL))
           AND ((status = 'REVERSED') = (reversed_by IS NOT NULL))
           AND ((status = 'REVERSED') = (reversed_at IS NOT NULL))),

    -- The pair rule, STRICTER AT REST than the aggregate and deliberately so: in memory an
    -- equal pair is admitted while INITIATED (unjudged input, whose one legal exit is the
    -- SELF_TRANSFER refusal), but INITIATED is never durably observed - so at rest the equal
    -- pair is legal in exactly one shape, the committed record of refusing exactly that
    -- mistake. IS NOT DISTINCT FROM, because a NULL reason must read as "not SELF_TRANSFER"
    -- rather than making the CHECK vacuously pass.
    CONSTRAINT transfer_pair_differs_unless_self_refusal
        CHECK ((source_account_id = destination_account_id)
             = (failure_reason IS NOT DISTINCT FROM 'SELF_TRANSFER')),

    -- Application-supplied from the injected Clock, never DEFAULT now() (P0-TSK-015's rule).
    initiated_by           uuid        NOT NULL,
    initiated_at           timestamptz NOT NULL,

    CONSTRAINT transfer_reversal_is_not_before_initiation
        CHECK (reversed_at >= initiated_at)
);

-- Serves "this customer's transfers" - P4-TSK-008's list and status reads, named now rather
-- than discovered by that task (the V004 index-the-read precedent).
CREATE INDEX transfer_by_customer ON transfers.transfer (customer_id);

-- The machine's edges, for EVERY writer, the migrator included (the V010 shape). Two halves:
-- everything outside the reversal columns is FROZEN - what the customer was told happened is
-- what stays recorded - and a status move must be one of the machine's own edges, the
-- conditions generated from TransferStatus.permittedTransitions(). The INITIATED-source edges
-- are here because the machine has them, and are simultaneously dead at rest: an update out of
-- a planted INITIATED row cannot supply its reason or entry, those columns being frozen - the
-- layers agreeing, not disagreeing.
CREATE OR REPLACE FUNCTION transfers.transfer_permits_only_machine_edges()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.id <> NEW.id
        OR OLD.customer_id <> NEW.customer_id
        OR OLD.source_account_id <> NEW.source_account_id
        OR OLD.destination_account_id <> NEW.destination_account_id
        OR OLD.amount_minor <> NEW.amount_minor
        OR OLD.currency <> NEW.currency
        OR OLD.scale <> NEW.scale
        OR OLD.reference IS DISTINCT FROM NEW.reference
        OR OLD.failure_reason IS DISTINCT FROM NEW.failure_reason
        OR OLD.journal_entry_id IS DISTINCT FROM NEW.journal_entry_id
        OR OLD.initiated_by <> NEW.initiated_by
        OR OLD.initiated_at <> NEW.initiated_at THEN
        RAISE EXCEPTION 'a transfer''s record is immutable outside the reversal columns: what the customer was told happened is what stays recorded (P4-TSK-004, INV-HIST-01)';
    END IF;
    IF NOT ((OLD.status = 'INITIATED' AND NEW.status IN ('COMPLETED', 'FAILED'))
            OR (OLD.status = 'COMPLETED' AND NEW.status IN ('REVERSED'))) THEN
        RAISE EXCEPTION 'a transfer moves only along the machine''s edges: INITIATED -> {COMPLETED, FAILED}, COMPLETED -> REVERSED (ADR-0044, INV-LIFE-02/-04)';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER transfer_permits_only_machine_edges
    BEFORE UPDATE ON transfers.transfer
    FOR EACH ROW
    EXECUTE FUNCTION transfers.transfer_permits_only_machine_edges();

-- The append-only lifecycle history: the path a transfer took is evidence rather than memory
-- (ADR-0044). Order is SERVER-ASSIGNED - GENERATED ALWAYS, so no instance's clock or counter
-- decides which of two facts is later (the consent_record lesson). Edge validity is
-- deliberately NOT constrained here: history is evidence written by the guarded writers, and
-- the authoritative row's trigger above is the control - a constraint on evidence would refuse
-- to record what a defective writer actually did.
CREATE TABLE transfers.transfer_event (
    id          bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Same schema, so the FK is legal and right: an event about a transfer that does not exist
    -- is not evidence of anything.
    transfer_id uuid        NOT NULL REFERENCES transfers.transfer (id),

    from_status text        NOT NULL
        CONSTRAINT transfer_event_from_status_is_known
            CHECK (from_status IN ('INITIATED', 'COMPLETED', 'FAILED', 'REVERSED')),
    to_status   text        NOT NULL
        CONSTRAINT transfer_event_to_status_is_known
            CHECK (to_status IN ('INITIATED', 'COMPLETED', 'FAILED', 'REVERSED')),

    -- Application-supplied, never DEFAULT now().
    actor_id    uuid        NOT NULL,
    occurred_at timestamptz NOT NULL
);

CREATE INDEX transfer_event_by_transfer ON transfers.transfer_event (transfer_id);

COMMENT ON TABLE transfers.transfer IS
    'One commanded movement of funds between two internal accounts: the judgement and its record (ADR-0044). The money itself is the ledger posting journal_entry_id names; nothing in this schema writes a posting (INV-LED-04, ADR-0043).';
COMMENT ON COLUMN transfers.transfer.customer_id IS
    'party.customer.id by value; no cross-schema FK by design (ADR-0029''s rule). Resolved from authoritative state by the execution command, never from a request.';
COMMENT ON COLUMN transfers.transfer.status IS
    'INITIATED -> {COMPLETED, FAILED}; COMPLETED -> REVERSED; FAILED/REVERSED terminal (INV-LIFE-04). INITIATED is never durably observed: the row commits with its outcome (ADR-0043).';
COMMENT ON TABLE transfers.transfer_event IS
    'Append-only lifecycle history: the path a transfer took, as evidence rather than memory. Server-assigned order; SELECT and INSERT only.';

-- THE GRANTS ARRIVE WITH THE TABLE (P4-TSK-001's floor made this available; PHASE_4_PLAN.md
-- section 8 names this exact set). SELECT and INSERT for the row's life; UPDATE narrowed to
-- the reversal columns - the ONLY legitimate update this table will ever see, and the
-- narrowing is what forces insert-carries-outcome: a FAILED outcome cannot arrive by UPDATE,
-- its reason column being ungranted. No DELETE: a transfer's end is a status, never an
-- absence.
GRANT SELECT, INSERT ON transfers.transfer TO finapp_app;
GRANT UPDATE (status, reversal_entry_id, reversed_by, reversed_at) ON transfers.transfer TO finapp_app;

-- The history is append-only at the privilege (the audit_record model): SELECT and INSERT,
-- nothing else, and no trigger is needed because no grant admits an edit.
GRANT SELECT, INSERT ON transfers.transfer_event TO finapp_app;
