-- Holds: reservations against available balance (P3-TSK-015, INV-BAL-04).
--
-- A hold is a claim against available balance, NOT a posting: value has not moved, so nothing
-- here touches the journal, and the journal's immutability regime does not apply wholesale.
-- What does apply is INV-LIFE-04 at DB-CONSTRAINT rank: a RELEASED hold is terminal for EVERY
-- writer, because a resurrected hold would re-reserve funds with no acting flow, no audit
-- record and no event - the trigger below is the review_task freeze (P2-TSK-012's precedent)
-- applied to the platform's first financial reservation.
--
-- WHAT THE SCHEMA DOES NOT CARRY, AND WHY
--   "A hold cannot make available balance negative" spans this table AND ledger.journal_line
--   (available = settled - active holds), and no CHECK sees across tables. The DOMAIN carries
--   the decision - HoldService derives both numbers from authoritative rows inside the account
--   row's FOR UPDATE (ADR-0039) - and the representable halves land here: the amount is
--   strictly positive, holds_minor on the projection row is CHECKed non-negative (V006), and
--   the terminal freeze keeps the standing-holds set monotonic per hold.
--
-- PHASE_3_PLAN §8 SAYS "partial unique where active", AND THAT SENTENCE HAS NO SUBJECT YET
--   One-active-per-something needs a something: the commanding reference (a transfer, an
--   authorization) that would make a duplicate placement detectable arrives with Phase 4's
--   flows, and several active holds per ACCOUNT is the normal case, not a defect. A reference
--   column nothing populates would be the recorded anti-pattern (confident javadoc on a dead
--   column), so the index below is partial and NOT unique - it serves the availability read -
--   and the plan carries a provenance note. Idempotent placement is the commanding flow's key
--   (INV-IDEM-01), whose transaction this table's rows join.

CREATE TABLE ledger.hold (
    -- UUIDv7, minted by the placing call (ADR-0013).
    id                uuid        PRIMARY KEY,

    ledger_account_id uuid        NOT NULL REFERENCES ledger.ledger_account (id),

    -- The ADR-0003 three-column monetary shape, generated by MoneyColumns.ColumnNames.ddl()
    -- and pinned verbatim by HoldMigrationTest so the shape cannot drift per table.
    amount_minor BIGINT NOT NULL, currency CHAR(3) NOT NULL, scale SMALLINT NOT NULL, CHECK (currency ~ '^[A-Z]{3}$'), CHECK (scale BETWEEN 0 AND 9),

    status            text        NOT NULL,

    -- Application-supplied from one injected Clock, never DEFAULT now() (P0-TSK-015).
    placed_at         timestamptz NOT NULL,
    released_at       timestamptz,

    -- Direction carries no sign here because there is no direction: a hold only ever
    -- subtracts from availability, and a "negative hold" is a release (INV-BAL-04).
    CONSTRAINT hold_amount_is_positive
        CHECK (amount_minor > 0),

    CONSTRAINT hold_status_is_known
        CHECK (status IN ('ACTIVE', 'RELEASED')),

    -- The status and the release instant are one fact, unsplittable for any writer.
    CONSTRAINT hold_release_instant_matches_status
        CHECK ((status = 'ACTIVE') = (released_at IS NULL)),

    CONSTRAINT hold_release_follows_placement
        CHECK (released_at IS NULL OR released_at >= placed_at),

    -- The V005 kind-binding mechanism: the referenced UNIQUE (id, currency) exists on
    -- ledger_account, so a hold's currency IS its account's for every writer (INV-MON-02) -
    -- a cross-currency hold could never be summed into the availability decision.
    CONSTRAINT hold_currency_matches_account
        FOREIGN KEY (ledger_account_id, currency)
        REFERENCES ledger.ledger_account (id, currency)
);

-- The availability read (HoldStore.findActiveFor): an account's STANDING holds. Partial,
-- because released holds leave the working set forever and must not grow the index the
-- hot decision path scans. Deliberately not unique - see the header.
CREATE INDEX hold_active_by_account
    ON ledger.hold (ledger_account_id)
    WHERE status = 'ACTIVE';

-- RELEASED is terminal for every writer, the migrator included (INV-LIFE-04 at
-- DB-CONSTRAINT rank). Exactly one edge exists: ACTIVE -> RELEASED, with the release
-- instant arriving in the same statement; identity and amount are immutable in any state.
-- The column-narrowed grant below already binds the application role; this binds everyone.
CREATE OR REPLACE FUNCTION ledger.hold_permits_only_release()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.id <> NEW.id
        OR OLD.ledger_account_id <> NEW.ledger_account_id
        OR OLD.amount_minor <> NEW.amount_minor
        OR OLD.currency <> NEW.currency
        OR OLD.scale <> NEW.scale
        OR OLD.placed_at <> NEW.placed_at THEN
        RAISE EXCEPTION 'a hold''s identity and amount are immutable (P3-TSK-015)';
    END IF;
    IF NOT (OLD.status = 'ACTIVE' AND NEW.status = 'RELEASED') THEN
        RAISE EXCEPTION 'the only edge a hold has is ACTIVE -> RELEASED (INV-LIFE-04)';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER hold_permits_only_release
    BEFORE UPDATE ON ledger.hold
    FOR EACH ROW
    EXECUTE FUNCTION ledger.hold_permits_only_release();

COMMENT ON TABLE ledger.hold IS
    'Reservations against available balance (INV-BAL-04): available = settled minus active '
    'holds, decided from postings and these rows inside the account row lock (ADR-0039), '
    'never from the projection (INV-BAL-05). RELEASED is terminal; a new reservation is a '
    'new row.';

-- SELECT and INSERT, plus UPDATE narrowed to exactly the release transition's columns
-- (PHASE_3_PLAN section 8; the V004 column-narrowing precedent). No DELETE: a hold is
-- evidence of a reservation that stood, and the availability history must stay explainable.
GRANT SELECT, INSERT ON ledger.hold TO finapp_app;
GRANT UPDATE (status, released_at) ON ledger.hold TO finapp_app;
