-- Adjustment proposals: four-eyes on manual adjustments (P3-TSK-021, INV-AUD-04).
--
-- Four-eyes is TWO AUTHENTICATED ACTS, never one request carrying two names: an initiator
-- proposes (nothing posts), and a SECOND person approves - the journal entry is posted in
-- the approval's own transaction. The threshold is deliberately "every adjustment"
-- (INV-REV-04 permits thresholds; a threshold is a per-currency amount policy - a versioned
-- artefact, INV-HIST-04 - with nothing to calibrate it yet, and a cross-currency threshold
-- is INV-MON-04's trap wearing policy clothes; a de-minimis threshold arrives later as a
-- pinned policy artefact, and unconditional is a strengthening, never a weakening).
--
-- THE INVARIANT'S OWN ENFORCE CLAUSE LANDS HERE, AT DB-CONSTRAINT RANK, TWICE
--   1. approver <> initiator is a plain CHECK on this table - representable because the
--      table is new, so no history can violate it (INV-HIST-01 untouched).
--   2. An ADJUSTMENT journal entry cannot COMMIT unless an APPROVED proposal references it:
--      the deferred constraint trigger below, the V004 mechanism, binding raw SQL and every
--      future writer. New rows only by nature, so pre-four-eyes history stays valid.
--
-- THE APPROVER APPROVES WHAT THEY READ, STRUCTURALLY (TOCTOU closed at the schema)
--   The proposal's payload - dates, reference, reason, initiator - is immutable by trigger
--   for EVERY writer, and its lines are append-only with no UPDATE grant at all. The only
--   edges any writer has are PROPOSED -> APPROVED and PROPOSED -> REJECTED, each terminal
--   (INV-LIFE-04), each arriving with its decision columns in the same statement.

CREATE TABLE ledger.adjustment_proposal (
    -- UUIDv7, minted by the proposing call (ADR-0013).
    id                uuid        PRIMARY KEY,

    status            text        NOT NULL,

    -- The entry these lines will become, fixed at proposal time: the approver must be able
    -- to read exactly what will post (DOMAIN_MODEL.md section Time - both dates are domain
    -- inputs, never clock reads).
    posting_date      date        NOT NULL,
    value_date        date        NOT NULL,

    -- V004's own bounds, restated because these columns BECOME journal_entry's at approval:
    -- a proposal the journal would refuse must be unstorable here too.
    reference         text        NOT NULL,
    reason            text        NOT NULL,

    proposed_by       text        NOT NULL,
    -- Application-supplied from one injected Clock, never DEFAULT now() (P0-TSK-015).
    proposed_at       timestamptz NOT NULL,

    decided_by        text,
    decided_at        timestamptz,

    -- The entry the approval posted. UNIQUE: one proposal, at most one entry - and the
    -- deferred trigger below is what makes the converse hold for every writer.
    journal_entry_id  uuid        UNIQUE REFERENCES ledger.journal_entry (id),

    CONSTRAINT adjustment_proposal_status_is_known
        CHECK (status IN ('PROPOSED', 'APPROVED', 'REJECTED')),

    -- INV-AUD-04's Enforce clause, verbatim: approver <> initiator, at DB-CONSTRAINT rank.
    -- On the new table this is a plain CHECK - no history predates it, so no predicate
    -- narrowing and no migration debt.
    CONSTRAINT adjustment_proposal_approver_is_not_initiator
        CHECK (status <> 'APPROVED' OR decided_by <> proposed_by),

    -- The status and its decision columns are one fact, unsplittable for any writer.
    CONSTRAINT adjustment_proposal_decision_matches_status
        CHECK ((status = 'PROPOSED') = (decided_by IS NULL)),
    CONSTRAINT adjustment_proposal_decision_instant_matches_status
        CHECK ((status = 'PROPOSED') = (decided_at IS NULL)),
    CONSTRAINT adjustment_proposal_entry_matches_status
        CHECK ((status = 'APPROVED') = (journal_entry_id IS NOT NULL)),

    CONSTRAINT adjustment_proposal_decision_follows_proposal
        CHECK (decided_at IS NULL OR decided_at >= proposed_at),

    CONSTRAINT adjustment_proposal_reference_is_bounded
        CHECK (length(reference) BETWEEN 1 AND 200),
    CONSTRAINT adjustment_proposal_reason_is_bounded
        CHECK (length(reason) BETWEEN 1 AND 1000),
    CONSTRAINT adjustment_proposal_proposed_by_is_bounded
        CHECK (length(proposed_by) BETWEEN 1 AND 200),
    CONSTRAINT adjustment_proposal_decided_by_is_bounded
        CHECK (decided_by IS NULL OR length(decided_by) BETWEEN 1 AND 200)
);

CREATE TABLE ledger.adjustment_proposal_line (
    proposal_id       uuid     NOT NULL REFERENCES ledger.adjustment_proposal (id),

    -- Line order within the proposal; the approval rebuilds the entry's lines in this order.
    seq               smallint NOT NULL,

    ledger_account_id uuid     NOT NULL REFERENCES ledger.ledger_account (id),

    direction         text     NOT NULL,

    -- The ADR-0003 three-column monetary shape, generated by MoneyColumns.ColumnNames.ddl()
    -- and pinned verbatim by AdjustmentProposalMigrationTest.
    amount_minor BIGINT NOT NULL, currency CHAR(3) NOT NULL, scale SMALLINT NOT NULL, CHECK (currency ~ '^[A-Z]{3}$'), CHECK (scale BETWEEN 0 AND 9),

    CONSTRAINT adjustment_proposal_line_direction_is_known
        CHECK (direction IN ('DEBIT', 'CREDIT')),

    CONSTRAINT adjustment_proposal_line_amount_is_positive
        CHECK (amount_minor > 0),

    CONSTRAINT adjustment_proposal_line_seq_is_natural
        CHECK (seq >= 0),

    CONSTRAINT adjustment_proposal_line_pk
        PRIMARY KEY (proposal_id, seq),

    -- The V005 kind-binding mechanism: a proposal that could never post - a line in a
    -- currency foreign to its account - refuses at PROPOSAL time, for every writer.
    CONSTRAINT adjustment_proposal_line_currency_matches_account
        FOREIGN KEY (ledger_account_id, currency)
        REFERENCES ledger.ledger_account (id, currency)
);

-- The payload is frozen at creation and the machine has exactly two edges, for EVERY
-- writer, the migrator included: what the approver read is what posts, structurally.
-- Terminal states are terminal (INV-LIFE-04); the decision columns arrive with their edge
-- and never move again.
CREATE OR REPLACE FUNCTION ledger.adjustment_proposal_permits_only_decision()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.id <> NEW.id
        OR OLD.posting_date <> NEW.posting_date
        OR OLD.value_date <> NEW.value_date
        OR OLD.reference <> NEW.reference
        OR OLD.reason <> NEW.reason
        OR OLD.proposed_by <> NEW.proposed_by
        OR OLD.proposed_at <> NEW.proposed_at THEN
        RAISE EXCEPTION 'a proposal''s payload is immutable: the approver approves what they read (P3-TSK-021, INV-AUD-04)';
    END IF;
    IF NOT (OLD.status = 'PROPOSED'
            AND NEW.status IN ('APPROVED', 'REJECTED')) THEN
        RAISE EXCEPTION 'a proposal''s only edges are PROPOSED -> APPROVED and PROPOSED -> REJECTED (INV-LIFE-04)';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER adjustment_proposal_permits_only_decision
    BEFORE UPDATE ON ledger.adjustment_proposal
    FOR EACH ROW
    EXECUTE FUNCTION ledger.adjustment_proposal_permits_only_decision();

-- A proposal's lines are what the approver read: never edited, never removed, by anybody.
CREATE OR REPLACE FUNCTION ledger.adjustment_proposal_line_is_frozen()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'a proposal''s lines are immutable: the approver approves what they read (P3-TSK-021)';
END;
$$;

CREATE TRIGGER adjustment_proposal_line_is_frozen
    BEFORE UPDATE OR DELETE ON ledger.adjustment_proposal_line
    FOR EACH ROW
    EXECUTE FUNCTION ledger.adjustment_proposal_line_is_frozen();

-- INV-AUD-04 at the JOURNAL, for every writer (the V004 deferred-trigger mechanism): an
-- ADJUSTMENT entry cannot COMMIT unless an APPROVED proposal references it - and the CHECK
-- above guarantees an APPROVED proposal names two distinct people. Fires on NEW entry rows
-- only, so pre-four-eyes history (P3-TSK-017's one-person adjustments) stays untouched
-- (INV-HIST-01). Judged at COMMIT because the approval transaction inserts the entry FIRST
-- and links the proposal after - the whole is judged when the whole exists.
CREATE OR REPLACE FUNCTION ledger.adjustment_entry_is_approved()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.entry_type = 'ADJUSTMENT'
        AND NOT EXISTS (
            SELECT 1
            FROM ledger.adjustment_proposal proposal
            WHERE proposal.journal_entry_id = NEW.id
              AND proposal.status = 'APPROVED') THEN
        RAISE EXCEPTION 'an adjustment entry requires an approved proposal by a second person (INV-AUD-04)'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER adjustment_entry_is_approved
    AFTER INSERT ON ledger.journal_entry
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW
    EXECUTE FUNCTION ledger.adjustment_entry_is_approved();

COMMENT ON TABLE ledger.adjustment_proposal IS
    'Four-eyes on manual adjustments (INV-AUD-04): the initiator proposes, a second person '
    'approves, and the journal entry posts in the approval''s transaction. The payload is '
    'frozen at creation, both terminal states are terminal, and an ADJUSTMENT entry cannot '
    'commit without an APPROVED proposal referencing it.';

-- SELECT and INSERT, plus UPDATE narrowed to exactly the decision's columns (the V004
-- column-narrowing precedent). No DELETE: a proposal - approved, rejected or standing - is
-- the evidence of who asked to move value and who answered.
GRANT SELECT, INSERT ON ledger.adjustment_proposal TO finapp_app;
GRANT UPDATE (status, decided_by, decided_at, journal_entry_id)
    ON ledger.adjustment_proposal TO finapp_app;
GRANT SELECT, INSERT ON ledger.adjustment_proposal_line TO finapp_app;
