package com.finapp.consent;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * The consent schema and the code that writes it are one definition (`P2-TSK-017`) — the
 * {@code ReviewTaskMigrationTest} idiom. The sharper artefacts here are the grants: the record
 * table's {@code SELECT, INSERT} and nothing else IS {@code INV-CNS-02}, and the text table's
 * {@code SELECT} alone is what makes a consent text a migration-reviewed artefact rather than a
 * row the application can quietly rewrite.
 */
@DisplayName("the consent schema and the code agree (P2-TSK-017)")
class ConsentMigrationTest {

    private static final String MIGRATION =
            "db/migration/consent/V002__create_consent_text_and_record.sql";

    @Test
    @DisplayName("both purpose constraints list exactly what the enum declares")
    void purposeConstraintsMatchTheEnum() {
        // Two tables, two constraints, one enum: a purpose added to the code without both
        // constraints widening is a value the domain produces and the database refuses,
        // failing at the last write (the V005/IdentityEnumMigrationTest lesson).
        assertThat(countOf(migration(), "CHECK (purpose IN (" + ConsentPurpose.sqlValueList() + "))"))
                .as("consent_text and consent_record each constrain the purpose")
                .isEqualTo(2);
    }

    @Test
    @DisplayName("the action constraint lists exactly what the enum declares")
    void actionConstraintMatchesTheEnum() {
        assertThat(migration())
                .contains("CHECK (action IN (" + ConsentAction.sqlValueList() + "))");
    }

    @Test
    @DisplayName("the record table's grants are SELECT and INSERT, and nothing else")
    void recordGrantsAreThePrivilegeModel() {
        assertThat(migration())
                .contains("GRANT SELECT, INSERT ON consent.consent_record TO finapp_app")
                .as("an UPDATE or DELETE grant here is INV-CNS-02 repealed")
                .doesNotContain("UPDATE ON consent.consent_record")
                .doesNotContain("DELETE ON consent.consent_record");
    }

    @Test
    @DisplayName("the text table grants SELECT alone - texts arrive only by migration")
    void textsAreUnwritableByTheApplication() {
        assertThat(migration())
                .contains("GRANT SELECT ON consent.consent_text TO finapp_app")
                .doesNotContain("INSERT ON consent.consent_text TO")
                .doesNotContain("UPDATE ON consent.consent_text")
                .doesNotContain("DELETE ON consent.consent_text");
    }

    @Test
    @DisplayName("the version pin is composite - a record cannot pin another purpose's text")
    void theVersionPinIsComposite() {
        // The V008 lesson: two single-column FKs would let a record reference an artefact the
        // person was never shown; the composite makes the pinned version a version OF THIS
        // purpose at DB-CONSTRAINT rank.
        assertThat(migration())
                .contains("FOREIGN KEY (purpose, text_version)")
                .contains("REFERENCES consent.consent_text (purpose, version)");
    }

    @Test
    @DisplayName("the order of the history is server-assigned, and no client can supply it")
    void theOrderIsTheServers() {
        assertThat(migration())
                .as("GENERATED ALWAYS refuses client-supplied values - BY DEFAULT would accept"
                        + " them, and an instance's own counter deciding which racing fact is"
                        + " later is exactly what the backlog's P0-TST-009 citation forbids")
                .contains("GENERATED ALWAYS AS IDENTITY")
                .doesNotContain("GENERATED BY DEFAULT");
    }

    @Test
    @DisplayName("every enum member's v1 text is seeded, so currentTextFor cannot come up empty")
    void everyPurposeHasASeededText() {
        String migration = migration();
        for (ConsentPurpose purpose : ConsentPurpose.values()) {
            assertThat(migration)
                    .as("a purpose without a seeded text is a purpose nothing can grant against")
                    .contains("('" + purpose.name() + "', 1,");
        }
    }

    @Test
    @DisplayName("no cross-schema foreign key")
    void partyIsReferencedByValue() {
        assertThat(migration())
                .doesNotContain("REFERENCES party.")
                .doesNotContain("REFERENCES identity.")
                .doesNotContain("REFERENCES kyc.");
    }

    // -----------------------------------------------------------------

    private static int countOf(String text, String needle) {
        int count = 0;
        int from = 0;
        while ((from = text.indexOf(needle, from)) >= 0) {
            count++;
            from += needle.length();
        }
        return count;
    }

    /** From the classpath, the sibling migration tests' idiom. */
    private static String migration() {
        try (InputStream stream =
                ConsentMigrationTest.class.getClassLoader().getResourceAsStream(MIGRATION)) {
            if (stream == null) {
                throw new IllegalStateException("Migration not on the test classpath: " + MIGRATION);
            }
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
