-- The checkout session, its history, and the order a paid one produces (P6-TSK-006, ADR-0053).
--
-- EVERY GENERATED LIST BELOW HAS ONE DEFINITION: the status CHECKs come from
-- CheckoutSessionStatus.sqlValueList(), the transition trigger's edge conditions from
-- permittedTransitions(), the line-summary bound from CheckoutSession.MAX_LINE_SUMMARY_LENGTH,
-- the token hash's shape and its algorithm from CheckoutSessionToken.
-- CheckoutSessionMigrationTest fails the build if this file and the code disagree.
--
-- NO CROSS-SCHEMA FOREIGN KEYS, ANYWHERE HERE (ADR-0029) - and this table has FOUR outward
-- references, which makes it the clearest statement of the rule in the platform:
-- merchant_ref -> merchant.merchant, fee_schedule_version_ref -> merchant.fee_schedule_version,
-- payment_intent_ref -> payments.payment_intent, captured_entry_ref -> ledger.journal_entry.
-- All four travel BY VALUE. The checkout module cannot see any of those modules at build time
-- either: it depends on platform and nothing else, so these are uuid columns rather than typed
-- identifiers, which is the isolation showing up in the schema as well as in the type system.
--
-- AN OFFER IS NOT AN ORDER. A session that expires unpaid leaves NO ROW in checkout_order -
-- the platform does not manufacture commercial facts out of silence (ADR-0053 section 1). That
-- is why the order table has no status column and no session status is copied into it.
--
-- EXPIRY IS A STATE, NOT A FILTER (ADR-0053 section 4). expires_at is DATA the sweeper reads;
-- EXPIRED is a state the sweeper EARNS, with a history row, so the condition is countable and
-- auditable. A `WHERE expires_at < now()` read pretending to be a state would be invisible to
-- both. The application ALSO checks the clock before starting anything (CheckoutSession.confirm)
-- - not as a substitute for the state, but because a sweeper one minute behind is a minute in
-- which money would land on a dead offer.

CREATE TABLE checkout.checkout_session (
    -- UUIDv7, minted by the application (ADR-0013).
    id                       uuid        PRIMARY KEY,

    -- merchant.merchant.id by value (ADR-0029).
    merchant_ref             uuid        NOT NULL,

    -- The ADR-0003 three-column monetary shape, generated by MoneyColumns.ColumnNames.ddl().
    amount_minor BIGINT NOT NULL, amount_currency CHAR(3) NOT NULL, amount_scale SMALLINT NOT NULL, CHECK (amount_currency ~ '^[A-Z]{3}$'), CHECK (amount_scale BETWEEN 0 AND 9),

    -- A zero-amount checkout asserts nothing and a negative one is a refund wearing a
    -- purchase's clothes (the aggregate's own constructor invariant, for the writer that never
    -- ran it).
    CONSTRAINT checkout_session_amount_is_positive
        CHECK (amount_minor > 0),

    -- What the customer is being asked to pay for, as the merchant describes it. DISPLAY DATA,
    -- and classified as what it is: a line summary says what one person is buying.
    line_summary             text        NOT NULL
        CONSTRAINT checkout_session_line_summary_bounded
            CHECK (length(line_summary) BETWEEN 1 AND 1000),

    -- INV-HIST-04's pin, at the moment the price is AGREED: the customer sees the amount here
    -- and the merchant is quoted its terms here, so this is where the version is fixed.
    -- P6-TSK-007 copies it onto the payment's own pin and the capture prices under it, so a
    -- schedule version created while a customer is at the payment page reprices nothing
    -- (INV-MER-03, ADR-0050 section 5).
    fee_schedule_version_ref uuid        NOT NULL,

    -- THERE IS NO COLUMN FOR A TOKEN, AND THAT IS THE DESIGN (INV-IDN-01). What is stored is a
    -- SHA-256 hash of 32 random bytes, with the algorithm that produced it recorded beside it
    -- (INV-IDN-02). Bounded to base64-of-SHA-256's exact shape so a column that somehow
    -- received a plaintext token would not fit quietly.
    token_hash               text        NOT NULL
        CONSTRAINT checkout_session_token_hash_shape
            CHECK (token_hash ~ '^[A-Za-z0-9+/]{43}=$'),
    -- Named `algorithm`, as merchant_api_key already names the same thing - and because
    -- `token_algorithm` READS like a secret to NoUnwrappedSecretRulesTest's name-based rule
    -- while holding the string 'SHA-256'. Wrapping a constant would have been the wrong answer.
    algorithm                text        NOT NULL
        CONSTRAINT checkout_session_algorithm_bounded
            CHECK (length(algorithm) BETWEEN 1 AND 50),

    -- payments.payment_intent.id by value; NULL until the customer confirms. SET ONCE - see the
    -- trigger. One payment intent per session (ADR-0053 section 3): a retry after a failed
    -- payment re-uses it, exactly as ADR-0045 section 4 allows for attempts one level down.
    payment_intent_ref       uuid,

    status                   text        NOT NULL
        CONSTRAINT checkout_session_status_is_known
            CHECK (status IN ('OPEN', 'PAYMENT_PENDING', 'COMPLETED', 'COMPLETED_LATE', 'EXPIRED', 'ABANDONED')),

    -- Application-supplied from one injected Clock, never DEFAULT now().
    expires_at               timestamptz NOT NULL,
    created_at               timestamptz NOT NULL,
    status_changed_at        timestamptz NOT NULL,

    -- An offer that expires before it exists is not an offer.
    CONSTRAINT checkout_session_expires_after_creation
        CHECK (expires_at > created_at),
    CONSTRAINT checkout_session_status_change_is_not_before_creation
        CHECK (status_changed_at >= created_at)
);

-- ONE TOKEN, ONE SESSION, ACROSS THE PLATFORM. Not a per-merchant uniqueness: two sessions
-- sharing a token would let a holder act on a session that is not theirs, whoever owns the row.
-- At 32 bytes of entropy a collision is not a practical concern - this exists so that a defect
-- in generation (a fixed seed, a reused value, a test double reaching production) fails LOUDLY
-- at the insert rather than silently creating two doors with one key (merchant V003's reasoning).
CREATE UNIQUE INDEX checkout_session_one_row_per_token
    ON checkout.checkout_session (token_hash);

-- Serves "this merchant's sessions" - the surface P6-TSK-009 reads, named now rather than
-- discovered by that task (the index-the-read precedent).
CREATE INDEX checkout_session_by_merchant ON checkout.checkout_session (merchant_ref);

-- THE SWEEPER'S OWN READ (P6-TSK-008): live sessions past their deadline. Partial, so the
-- terminal states are not merely filtered but ABSENT from the index the sweeper scans.
CREATE INDEX checkout_session_live_by_deadline
    ON checkout.checkout_session (expires_at)
    WHERE status IN ('OPEN', 'PAYMENT_PENDING');

-- THE MACHINE'S EDGES BIND EVERY WRITER (INV-LIFE-02; the payment machines' idiom): the
-- aggregate refuses first in code, this trigger refuses raw SQL and the migrator alike.
--
-- TWO HALVES. Everything but status, status_changed_at and payment_intent_ref is FROZEN - a
-- session's offer is what it was when it was made, and changing the amount, the price pin or
-- the token after the fact is corruption whoever writes it. And payment_intent_ref is SET ONCE:
-- NULL -> a value is legal, a value -> anything else is not, so "one payment intent per session"
-- is a database fact rather than a convention (ADR-0053 section 3).
CREATE FUNCTION checkout.checkout_session_permits_only_machine_edges() RETURNS trigger
LANGUAGE plpgsql AS
$$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
            OR NEW.merchant_ref IS DISTINCT FROM OLD.merchant_ref
            OR NEW.amount_minor IS DISTINCT FROM OLD.amount_minor
            OR NEW.amount_currency IS DISTINCT FROM OLD.amount_currency
            OR NEW.amount_scale IS DISTINCT FROM OLD.amount_scale
            OR NEW.line_summary IS DISTINCT FROM OLD.line_summary
            OR NEW.fee_schedule_version_ref IS DISTINCT FROM OLD.fee_schedule_version_ref
            OR NEW.token_hash IS DISTINCT FROM OLD.token_hash
            OR NEW.algorithm IS DISTINCT FROM OLD.algorithm
            OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
            OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'a checkout session''s offer is frozen: only status, status_changed_at and the one payment intent reference ever change (INV-HIST-01)';
    END IF;
    IF OLD.payment_intent_ref IS NOT NULL
            AND NEW.payment_intent_ref IS DISTINCT FROM OLD.payment_intent_ref THEN
        RAISE EXCEPTION 'a checkout session opens ONE payment intent and keeps it: the reference is set once (ADR-0053 section 3)';
    END IF;
    IF NEW.status = OLD.status THEN
        RETURN NEW;
    END IF;
    IF NOT ((OLD.status = 'OPEN' AND NEW.status IN ('PAYMENT_PENDING', 'EXPIRED', 'ABANDONED'))
            OR (OLD.status = 'PAYMENT_PENDING' AND NEW.status IN ('COMPLETED', 'EXPIRED'))
            OR (OLD.status = 'EXPIRED' AND NEW.status IN ('COMPLETED_LATE'))) THEN
        RAISE EXCEPTION 'a checkout session moves only along the machine''s edges: OPEN -> {PAYMENT_PENDING, EXPIRED, ABANDONED}, PAYMENT_PENDING -> {COMPLETED, EXPIRED}, EXPIRED -> {COMPLETED_LATE} (ADR-0053, INV-LIFE-02/-04)';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER checkout_session_permits_only_machine_edges
    BEFORE UPDATE ON checkout.checkout_session
    FOR EACH ROW
    EXECUTE FUNCTION checkout.checkout_session_permits_only_machine_edges();

CREATE TABLE checkout.checkout_session_event (
    id          bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Same schema, so the FK is legal and right.
    session_id  uuid        NOT NULL REFERENCES checkout.checkout_session (id),

    from_status text        NOT NULL
        CONSTRAINT checkout_session_event_from_status_is_known
            CHECK (from_status IN ('OPEN', 'PAYMENT_PENDING', 'COMPLETED', 'COMPLETED_LATE', 'EXPIRED', 'ABANDONED')),
    to_status   text        NOT NULL
        CONSTRAINT checkout_session_event_to_status_is_known
            CHECK (to_status IN ('OPEN', 'PAYMENT_PENDING', 'COMPLETED', 'COMPLETED_LATE', 'EXPIRED', 'ABANDONED')),

    -- The audit_record actor model, as merchant V002 and payments V006 hold it: a session
    -- transition can be a person's act (the customer confirming, the merchant abandoning) or
    -- the platform's (the sweeper expiring, an outcome completing), and the vocabulary already
    -- speaks for both.
    actor_id    text        NOT NULL
        CONSTRAINT checkout_session_event_actor_id_bounded
            CHECK (length(actor_id) BETWEEN 1 AND 200),
    actor_type  text        NOT NULL
        CONSTRAINT checkout_session_event_actor_type_bounded
            CHECK (length(actor_type) BETWEEN 1 AND 50),

    occurred_at timestamptz NOT NULL
);

CREATE INDEX checkout_session_event_by_session
    ON checkout.checkout_session_event (session_id);

-- -----------------------------------------------------------------------------------------
-- The order: a fact, barely a machine.
-- -----------------------------------------------------------------------------------------
CREATE TABLE checkout.checkout_order (
    id                 uuid        PRIMARY KEY,

    -- ONE ORDER PER SESSION, TOTAL. A second order for one session would be a second
    -- commercial fact from one purchase; refused by the key rather than by a read-then-write,
    -- so ten concurrent completions cannot both win.
    session_ref        uuid        NOT NULL UNIQUE REFERENCES checkout.checkout_session (id),

    -- merchant.merchant.id by value (ADR-0029). Copied from the session so a merchant's order
    -- listing needs no join across a boundary that has none.
    merchant_ref       uuid        NOT NULL,

    amount_minor BIGINT NOT NULL, amount_currency CHAR(3) NOT NULL, amount_scale SMALLINT NOT NULL, CHECK (amount_currency ~ '^[A-Z]{3}$'), CHECK (amount_scale BETWEEN 0 AND 9),
    CONSTRAINT checkout_order_amount_is_positive
        CHECK (amount_minor > 0),

    -- ledger.journal_entry.id by value: the entry that PAID for this order (ADR-0050 section
    -- 3's four lines). This is what makes a merchant's statement traceable end to end without
    -- this module being able to see the ledger at all.
    captured_entry_ref uuid        NOT NULL,

    created_at         timestamptz NOT NULL
);

CREATE INDEX checkout_order_by_merchant ON checkout.checkout_order (merchant_ref);

-- NO STATUS COLUMN, DELIBERATELY. An order that exists is PAID - it is created in the
-- completion's own transaction and never before, so there is no unpaid order to model. Refund
-- standing is DERIVED from the payment's refund rows at read time (ADR-0053 section 6), never
-- stored: a REFUNDED flag here would be a second authority beside the rows that actually moved
-- the money. And fulfilment - shipped, delivered, returned - is the merchant's business,
-- outside the platform's books.
--
-- APPEND-ONLY AT EVERY RANK. An order is evidence, and evidence that can be edited is worth
-- less than none.
--
-- ITS OWN FUNCTION, NOT merchant.fee_definitions_are_immutable(). P6-TSK-005 reused V004's
-- function WITHIN the merchant schema and recorded why: two functions saying "never" would
-- eventually say it differently. ACROSS schemas the reasoning inverts - a schema that depends
-- on another schema's function cannot be created, dropped or reasoned about on its own, and
-- schema isolation is the stronger property here. The duplication is one RAISE.
CREATE FUNCTION checkout.orders_are_immutable() RETURNS trigger
LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION 'an order is a fact: it is created when a payment captures and never changes (ADR-0053 section 6, INV-HIST-01). Operation %', TG_OP;
END;
$$;

CREATE TRIGGER checkout_order_is_immutable
    BEFORE UPDATE OR DELETE ON checkout.checkout_order
    FOR EACH ROW
    EXECUTE FUNCTION checkout.orders_are_immutable();

COMMENT ON TABLE checkout.checkout_session IS
    'A merchant''s short-lived offer to a customer to pay (ADR-0053). Six states; expiry is a state the sweeper EARNS, never a filter. A session that dies unpaid produces NO order.';
COMMENT ON COLUMN checkout.checkout_session.token_hash IS
    'SHA-256 of 32 random bytes, never a token (INV-IDN-01). Single-purpose: possession grants access to THIS session and nothing else - a leaked checkout token buys one stranger''s pending purchase, not an account.';
COMMENT ON COLUMN checkout.checkout_session.payment_intent_ref IS
    'SET ONCE, by the trigger: one payment intent per session (ADR-0053 section 3). A retry after a failed payment re-uses it.';
COMMENT ON COLUMN checkout.checkout_session.fee_schedule_version_ref IS
    'INV-HIST-04''s pin at the moment the price is agreed. P6-TSK-007 copies it onto the payment''s pin; the capture prices under it (INV-MER-03).';
COMMENT ON TABLE checkout.checkout_session_event IS
    'Append-only lifecycle history: the path a session took, as evidence rather than memory. Server-assigned order; SELECT and INSERT only.';
COMMENT ON TABLE checkout.checkout_order IS
    'The permanent commercial fact a PAID session produces, one per session. No status column: an order that exists is paid, and refund standing is derived from the payment''s refund rows, never stored.';
COMMENT ON COLUMN checkout.checkout_order.captured_entry_ref IS
    'The ledger journal entry that paid for this order, by value (ADR-0029) - the traceable chain''s last link: order -> entry -> ADR-0050 section 3''s four lines.';

-- THE GRANTS ARRIVE WITH THE TABLES (P6-TSK-001's floor).
--
-- The session: SELECT and INSERT for the row's life; UPDATE narrowed to the three columns that
-- ever legitimately change. No DELETE: a session's end is a status, never an absence.
GRANT SELECT, INSERT ON checkout.checkout_session TO finapp_app;
GRANT UPDATE (status, status_changed_at, payment_intent_ref) ON checkout.checkout_session TO finapp_app;

-- The history is append-only at the privilege (the audit_record model). No sequence grant: an
-- IDENTITY column's sequence is usable through the table's own INSERT privilege.
GRANT SELECT, INSERT ON checkout.checkout_session_event TO finapp_app;

-- The order: SELECT and INSERT only. The withheld UPDATE is the first rank of the append-only
-- claim; the trigger above exists for the writer the grants cannot bind.
GRANT SELECT, INSERT ON checkout.checkout_order TO finapp_app;
