-- The payment intent and its lifecycle history (P5-TSK-008, ADR-0045).
--
-- THE CUSTOMER'S OBJECTIVE, NEVER THE TRY AND NEVER THE MONEY. Every provider fact lives on
-- payment_attempt, refund totals live on the refund rows (derived by views, stored nowhere),
-- and the ledger's first touch is the capture's posting (ADR-0048) - so this row's coherence
-- is status-independent by design, and NOTHING BUT STATUS EVER CHANGES AFTER BIRTH. The
-- UPDATE grant below is therefore ONE COLUMN, which is the aggregate's per-field assertion
-- (PaymentIntentTest#aTransitionChangesTheStatusAndNothingElse) arriving at the privilege.
--
-- EVERY GENERATED LIST BELOW HAS ONE DEFINITION. The status CHECKs come from
-- PaymentIntentStatus.sqlValueList(), the monetary shape from MoneyColumns.ColumnNames.ddl(),
-- and the transition trigger's edge conditions from
-- PaymentIntentStatus.permittedTransitions(). PaymentsMigrationTest fails the build if this
-- file and the code disagree (the P0-TSK-022 pattern) - and it retires the SQL-literal pins
-- P5-TSK-006 carried in PaymentIntentTest against exactly this consumer arriving.
--
-- NO CROSS-SCHEMA FOREIGN KEYS, DELIBERATELY (ADR-0029): party_id and customer_id reference
-- party's tables, payment_method_id references paymentmethods.payment_method and
-- wallet_account_id references ledger.ledger_account - all by value. The create command
-- resolves every one of them from authoritative state (P5-TSK-009), and the payments module
-- cannot even compile against the PCI module (INV-PAY-02, M7).
--
-- UNLIKE THE TRANSFER, THE BIRTH STATE IS DURABLY OBSERVED (ADR-0045's inversion of
-- ADR-0044): creation commits REQUIRES_CONFIRMATION, which is precisely the window that
-- gives CANCELLED its producer. The row is born without an outcome and earns one by UPDATE -
-- which is why the trigger's edge conditions matter here in a way V002's transfer never
-- exercised for its INITIATED sources.

CREATE TABLE payments.payment_intent (
    -- UUIDv7, minted by the application (ADR-0013).
    id                uuid        PRIMARY KEY,

    -- The instrument's owner (a payment method is the PARTY's, P5-TSK-004) and the wallet
    -- product's owner (P3-TSK-012): the intent joins two ownerships, so it records both.
    party_id          uuid        NOT NULL,
    customer_id       uuid        NOT NULL,

    -- The paymentmethods row's identifier - never the token, never anything reconstructable
    -- (INV-PAY-02). The instrument resolves through a port app implements (P5-TSK-009).
    payment_method_id uuid        NOT NULL,

    -- The wallet's ledger account - where the capture will credit (ADR-0048).
    wallet_account_id uuid        NOT NULL,

    -- The ADR-0003 three-column monetary shape, generated by MoneyColumns.ColumnNames.ddl().
    amount_minor BIGINT NOT NULL, currency CHAR(3) NOT NULL, scale SMALLINT NOT NULL, CHECK (currency ~ '^[A-Z]{3}$'), CHECK (scale BETWEEN 0 AND 9),

    -- A zero top-up asserts nothing and a negative one is a credit wearing a debit's clothes
    -- (the aggregate's own constructor invariant, for the writer that never ran it).
    CONSTRAINT payment_intent_amount_is_positive
        CHECK (amount_minor > 0),

    -- Generated from PaymentIntentStatus.sqlValueList(). The machine lives on the enum and in
    -- the aggregate (INV-LIFE-02); this CHECK bounds what any writer can store, and the
    -- trigger below bounds how a stored value may move.
    status            text        NOT NULL
        CONSTRAINT payment_intent_status_is_known
            CHECK (status IN ('REQUIRES_CONFIRMATION', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),

    -- Application-supplied from the injected Clock, never DEFAULT now() (P0-TSK-015's rule).
    created_at        timestamptz NOT NULL
);

-- Serves "this customer's payments" - the status surface's read (P5-TSK-011), named now
-- rather than discovered by that task (the index-the-read precedent).
CREATE INDEX payment_intent_by_customer ON payments.payment_intent (customer_id);

-- The machine's edges, for EVERY writer, the migrator included (the transfers V002 shape).
-- Two halves: everything but status is FROZEN - the intent's coherence is status-independent,
-- so any other change is corruption whoever writes it - and a status move must be one of the
-- machine's own edges, the conditions generated from permittedTransitions(). No edge targets
-- REQUIRES_CONFIRMATION: birth is the only door, at the schema as at the aggregate.
CREATE OR REPLACE FUNCTION payments.payment_intent_permits_only_machine_edges()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.id <> NEW.id
        OR OLD.party_id <> NEW.party_id
        OR OLD.customer_id <> NEW.customer_id
        OR OLD.payment_method_id <> NEW.payment_method_id
        OR OLD.wallet_account_id <> NEW.wallet_account_id
        OR OLD.amount_minor <> NEW.amount_minor
        OR OLD.currency <> NEW.currency
        OR OLD.scale <> NEW.scale
        OR OLD.created_at <> NEW.created_at THEN
        RAISE EXCEPTION 'a payment intent changes nothing but its status after birth: every status-dependent fact lives where its fact lives (ADR-0045, INV-HIST-01)';
    END IF;
    IF NOT ((OLD.status = 'REQUIRES_CONFIRMATION' AND NEW.status IN ('PROCESSING', 'CANCELLED'))
            OR (OLD.status = 'PROCESSING' AND NEW.status IN ('SUCCEEDED', 'FAILED'))) THEN
        RAISE EXCEPTION 'a payment intent moves only along the machine''s edges: REQUIRES_CONFIRMATION -> {PROCESSING, CANCELLED}, PROCESSING -> {SUCCEEDED, FAILED} (ADR-0045, INV-LIFE-02/-04)';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER payment_intent_permits_only_machine_edges
    BEFORE UPDATE ON payments.payment_intent
    FOR EACH ROW
    EXECUTE FUNCTION payments.payment_intent_permits_only_machine_edges();

-- The append-only lifecycle history (the transfer_event ceremony): the path an intent took is
-- evidence rather than memory. Order is SERVER-ASSIGNED - GENERATED ALWAYS, so no instance's
-- clock decides which of two facts is later. Edge validity is deliberately NOT constrained
-- here: history is evidence written by the guarded writers, and the authoritative row's
-- trigger above is the control.
CREATE TABLE payments.payment_intent_event (
    id          bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Same schema, so the FK is legal and right.
    intent_id   uuid        NOT NULL REFERENCES payments.payment_intent (id),

    from_status text        NOT NULL
        CONSTRAINT payment_intent_event_from_status_is_known
            CHECK (from_status IN ('REQUIRES_CONFIRMATION', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    to_status   text        NOT NULL
        CONSTRAINT payment_intent_event_to_status_is_known
            CHECK (to_status IN ('REQUIRES_CONFIRMATION', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),

    -- Application-supplied, never DEFAULT now().
    actor_id    uuid        NOT NULL,
    occurred_at timestamptz NOT NULL
);

CREATE INDEX payment_intent_event_by_intent ON payments.payment_intent_event (intent_id);

COMMENT ON TABLE payments.payment_intent IS
    'The customer''s objective: fund my wallet with this amount from this instrument (ADR-0045). Never the try (payment_attempt owns every provider fact) and never the money (the ledger''s first touch is the capture''s posting, ADR-0048). Nothing but status changes after birth, and the UPDATE grant is that one column.';
COMMENT ON COLUMN payments.payment_intent.payment_method_id IS
    'paymentmethods.payment_method.id by value; no cross-schema FK by design (ADR-0029), and no compile-time edge to the PCI module at all (INV-PAY-02).';
COMMENT ON COLUMN payments.payment_intent.status IS
    'REQUIRES_CONFIRMATION -> {PROCESSING, CANCELLED}; PROCESSING -> {SUCCEEDED, FAILED}. SUCCEEDED is stable with no outgoing edge AND terminal: refund state is the refund rows'' fact (ADR-0045).';
COMMENT ON TABLE payments.payment_intent_event IS
    'Append-only lifecycle history: the path an intent took, as evidence rather than memory. Server-assigned order; SELECT and INSERT only.';

-- THE GRANTS ARRIVE WITH THE TABLE (P5-TSK-001's floor; PHASE_5_PLAN.md section 8). SELECT
-- and INSERT for the row's life; UPDATE narrowed to THE ONE COLUMN that ever legitimately
-- changes - the narrowing P5-TSK-006's per-field assertion promised this migration could
-- make. No DELETE: an intent's end is a status, never an absence.
GRANT SELECT, INSERT ON payments.payment_intent TO finapp_app;
GRANT UPDATE (status) ON payments.payment_intent TO finapp_app;

-- The history is append-only at the privilege (the audit_record model).
GRANT SELECT, INSERT ON payments.payment_intent_event TO finapp_app;
