-- The payment attempt and its lifecycle history (P5-TSK-008, ADR-0045, ADR-0046).
--
-- THE PROVIDER-FACING TRY: the row that owns EVERY provider fact - the per-operation
-- idempotency references we minted (INV-PAY-04), the references the provider answered with,
-- the amounts the issuer promised and the provider captured, and the mapped failure reason
-- (INV-PAY-03). This is what Phase 8 reconciles on.
--
-- UNLIKE THE INTENT, TRANSITIONS CARRY THEIR PAYLOADS - the fact arrives with the answer that
-- established it - so the UPDATE grant below is status PLUS the payload columns the doors
-- carry (the aggregate's per-field assertion, PaymentAttemptTest#aTransitionCarriesExactlyIts
-- Payload, arriving at the privilege), and the trigger holds the sharper rule the grant
-- cannot: A RECORDED PROVIDER FACT MOVES ONLY FROM NULL TO A VALUE, never edited and never
-- cleared - which is what refuses a payload edit smuggled inside a legal edge.
--
-- EVERY GENERATED LIST BELOW HAS ONE DEFINITION. The status CHECKs come from
-- PaymentAttemptStatus.sqlValueList(), the reason CHECK from
-- PaymentFailureReason.sqlValueList(), both monetary shapes from
-- MoneyColumns.ColumnNames.nullableDdl() (the fact arrives with a later transition), the
-- reference shapes from ProviderIdempotencyReference/ProviderReference (charset and
-- MAX_LENGTH), the transition trigger's edge conditions from permittedTransitions(), and the
-- one-live index predicate from sqlTerminalValueList(). PaymentsMigrationTest fails the build
-- if this file and the code disagree.
--
-- THE COHERENCE CHECKS ARE THE AGGREGATE'S CONSTRUCTOR, FOR THE WRITER THAT NEVER RAN IT:
-- stage facts per status (including FAILED's two legal shapes - AUTHORIZED -> FAILED is not
-- an edge, so a FAILED row holding the promise without a capture dispatch was written by no
-- path this machine permits), the promise as one fact, the captured pair exactly when
-- CAPTURED, and INV-PAY-05's row-local half: captured never exceeds authorized, same currency
-- and scale.
--
-- DELIBERATELY NO not-a-PAN CHECKs ON THE REFERENCE COLUMNS: these carry operation references
-- WE or the PROVIDER mint - never customer input - and a provider's all-numeric reference is
-- legitimate (many PSPs use numeric ids); refusing it would fail real payments. The PCI
-- boundary and its PAN sweep are paymentmethods' (P5-TSK-004), the module this one cannot
-- even compile against.
--
-- THE PROVIDER-REFERENCE UNIQUES ARE PLAIN, one provider existing in Phase 5; the per-provider
-- scope arrives with routing (Phase 7), beside the provider column that phase adds.

CREATE TABLE payments.payment_attempt (
    -- UUIDv7, minted by the application (ADR-0013) - the value the capture posting is keyed
    -- by (payment-capture:<attemptId>, ADR-0048).
    id                         uuid        PRIMARY KEY,

    -- Same schema, so the FK is legal and right (ADR-0029 forbids only cross-schema keys).
    intent_id                  uuid        NOT NULL REFERENCES payments.payment_intent (id),

    -- Our per-operation idempotency references (INV-PAY-04's representable half): the
    -- authorization's exists from birth - the dispatch commits before the provider is asked
    -- (ADR-0046), so no attempt row exists without it - and the capture's is minted by the
    -- capture dispatch. UNIQUE: one operation per reference, whichever instance minted it.
    -- Shape generated from ProviderIdempotencyReference (charset, MAX_LENGTH).
    auth_reference             text        NOT NULL UNIQUE
        CONSTRAINT payment_attempt_auth_reference_shape
            CHECK (auth_reference ~ '^[A-Za-z0-9-]{1,64}$'),
    capture_reference          text        UNIQUE
        CONSTRAINT payment_attempt_capture_reference_shape
            CHECK (capture_reference ~ '^[A-Za-z0-9-]{1,64}$'),

    -- The provider's own references (shape from ProviderReference), each arriving with its
    -- APPROVED answer and never before (ProviderAnswer's coherence).
    auth_provider_reference    text        UNIQUE
        CONSTRAINT payment_attempt_auth_provider_reference_shape
            CHECK (auth_provider_reference ~ '^[A-Za-z0-9_.:-]{1,128}$'),
    capture_provider_reference text        UNIQUE
        CONSTRAINT payment_attempt_capture_provider_reference_shape
            CHECK (capture_provider_reference ~ '^[A-Za-z0-9_.:-]{1,128}$'),

    -- The issuer's promise and the provider's capture: two nullable monetary facts, each
    -- generated by MoneyColumns.ColumnNames.nullableDdl() - present exactly when their
    -- transition has happened, all-or-nothing within each triple.
    authorized_amount_minor BIGINT, authorized_currency CHAR(3), authorized_scale SMALLINT, CHECK (authorized_currency ~ '^[A-Z]{3}$'), CHECK (authorized_scale BETWEEN 0 AND 9), CHECK ((authorized_amount_minor IS NULL) = (authorized_currency IS NULL) AND (authorized_amount_minor IS NULL) = (authorized_scale IS NULL)),
    captured_amount_minor BIGINT, captured_currency CHAR(3), captured_scale SMALLINT, CHECK (captured_currency ~ '^[A-Z]{3}$'), CHECK (captured_scale BETWEEN 0 AND 9), CHECK ((captured_amount_minor IS NULL) = (captured_currency IS NULL) AND (captured_amount_minor IS NULL) = (captured_scale IS NULL)),

    -- Generated from PaymentFailureReason.sqlValueList() - the mapped, enumerated reason
    -- (INV-PAY-03); the provider's own code lives only in retained evidence.
    failure_reason             text
        CONSTRAINT payment_attempt_failure_reason_is_known
            CHECK (failure_reason IN ('DECLINED', 'PROVIDER_UNAVAILABLE')),

    -- Generated from PaymentAttemptStatus.sqlValueList().
    status                     text        NOT NULL
        CONSTRAINT payment_attempt_status_is_known
            CHECK (status IN ('AUTH_DISPATCHED', 'AUTH_UNKNOWN', 'AUTHORIZED', 'CAPTURE_DISPATCHED', 'CAPTURE_UNKNOWN', 'CAPTURED', 'FAILED')),

    -- Application-supplied from the injected Clock, never DEFAULT now() (P0-TSK-015's rule).
    created_at                 timestamptz NOT NULL,

    -- The reason exists exactly when FAILED (the Transfer V002 rule; the aggregate's both
    -- directions at DB-CONSTRAINT rank).
    CONSTRAINT payment_attempt_reason_arrives_exactly_when_failed
        CHECK ((status = 'FAILED') = (failure_reason IS NOT NULL)),

    -- The issuer's promise is one fact: reference and amount together or not at all.
    CONSTRAINT payment_attempt_promise_is_one_fact
        CHECK ((auth_provider_reference IS NULL) = (authorized_amount_minor IS NULL)),

    -- The captured pair exactly when CAPTURED, both directions.
    CONSTRAINT payment_attempt_captured_pair_arrives_exactly_when_captured
        CHECK (((status = 'CAPTURED') = (captured_amount_minor IS NOT NULL))
           AND ((status = 'CAPTURED') = (capture_provider_reference IS NOT NULL))),

    -- Which facts each stage requires and forbids - the aggregate constructor's switch,
    -- verbatim. FAILED's rule is the two-legal-shapes rule: failed at authorization (bare) or
    -- failed at capture (promise and capture reference both present); a FAILED row holding
    -- the promise without a capture dispatch was written by no path (AUTHORIZED -> FAILED is
    -- VOIDED's job, absent until Phase 6).
    CONSTRAINT payment_attempt_stage_facts_match_status
        CHECK (CASE status
            WHEN 'AUTH_DISPATCHED'    THEN authorized_amount_minor IS NULL     AND capture_reference IS NULL
            WHEN 'AUTH_UNKNOWN'       THEN authorized_amount_minor IS NULL     AND capture_reference IS NULL
            WHEN 'AUTHORIZED'         THEN authorized_amount_minor IS NOT NULL AND capture_reference IS NULL
            WHEN 'CAPTURE_DISPATCHED' THEN authorized_amount_minor IS NOT NULL AND capture_reference IS NOT NULL
            WHEN 'CAPTURE_UNKNOWN'    THEN authorized_amount_minor IS NOT NULL AND capture_reference IS NOT NULL
            WHEN 'CAPTURED'           THEN authorized_amount_minor IS NOT NULL AND capture_reference IS NOT NULL
            WHEN 'FAILED'             THEN (authorized_amount_minor IS NULL) = (capture_reference IS NULL)
        END),

    -- Strictly positive when present (a CHECK over NULL is not false).
    CONSTRAINT payment_attempt_amounts_are_positive
        CHECK ((authorized_amount_minor IS NULL OR authorized_amount_minor > 0)
           AND (captured_amount_minor IS NULL OR captured_amount_minor > 0)),

    -- INV-PAY-05's row-local half: capture is bounded by authorization, in the capture's own
    -- currency and scale (summing across scales is meaningless - the V004 discipline).
    CONSTRAINT payment_attempt_capture_is_bounded_by_authorization
        CHECK (captured_amount_minor IS NULL
            OR (captured_currency = authorized_currency
                AND captured_scale = authorized_scale
                AND captured_amount_minor <= authorized_amount_minor))
);

-- ONE LIVE ATTEMPT PER INTENT - the concurrency arbiter for attempt creation (PHASE_5_PLAN.md
-- section 7): ten instances confirming one intent birth one attempt, and the losers converge.
-- PARTIAL, over the non-terminal states - the predicate generated from
-- sqlTerminalValueList() - which is the schema built for N attempts (ADR-0045 section 4): a
-- FAILED attempt frees the slot for the retry policy Phase 7 calibrates, while Phase 5's
-- commands ship exactly one attempt per intent.
CREATE UNIQUE INDEX payment_attempt_one_live_per_intent
    ON payments.payment_attempt (intent_id)
    WHERE status NOT IN ('CAPTURED', 'FAILED');

-- Serves the intent-attempt join (status surfaces and the outcome transactions).
CREATE INDEX payment_attempt_by_intent ON payments.payment_attempt (intent_id);

-- The machine's edges and the payload discipline, for EVERY writer. Three rules: the birth
-- facts are frozen; a recorded provider fact moves only from NULL to a value (never edited,
-- never cleared - what the customer's money was moved against is what stays recorded,
-- INV-HIST-01/-02); and a status move must be one of the machine's own edges, the conditions
-- generated from permittedTransitions(). The table CHECKs above then force each edge to carry
-- exactly its payload - the layers compose into the aggregate's door signatures.
CREATE OR REPLACE FUNCTION payments.payment_attempt_permits_only_machine_edges()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.id <> NEW.id
        OR OLD.intent_id <> NEW.intent_id
        OR OLD.auth_reference <> NEW.auth_reference
        OR OLD.created_at <> NEW.created_at THEN
        RAISE EXCEPTION 'a payment attempt''s birth facts are immutable: identity, intent and the dispatch reference are what the operation is (ADR-0046, INV-HIST-01)';
    END IF;
    IF (OLD.capture_reference IS NOT NULL AND NEW.capture_reference IS DISTINCT FROM OLD.capture_reference)
        OR (OLD.auth_provider_reference IS NOT NULL AND NEW.auth_provider_reference IS DISTINCT FROM OLD.auth_provider_reference)
        OR (OLD.capture_provider_reference IS NOT NULL AND NEW.capture_provider_reference IS DISTINCT FROM OLD.capture_provider_reference)
        OR (OLD.authorized_amount_minor IS NOT NULL AND NEW.authorized_amount_minor IS DISTINCT FROM OLD.authorized_amount_minor)
        OR (OLD.authorized_currency IS NOT NULL AND NEW.authorized_currency IS DISTINCT FROM OLD.authorized_currency)
        OR (OLD.authorized_scale IS NOT NULL AND NEW.authorized_scale IS DISTINCT FROM OLD.authorized_scale)
        OR (OLD.captured_amount_minor IS NOT NULL AND NEW.captured_amount_minor IS DISTINCT FROM OLD.captured_amount_minor)
        OR (OLD.captured_currency IS NOT NULL AND NEW.captured_currency IS DISTINCT FROM OLD.captured_currency)
        OR (OLD.captured_scale IS NOT NULL AND NEW.captured_scale IS DISTINCT FROM OLD.captured_scale)
        OR (OLD.failure_reason IS NOT NULL AND NEW.failure_reason IS DISTINCT FROM OLD.failure_reason) THEN
        RAISE EXCEPTION 'a recorded provider fact never changes: payload columns move only from NULL to a value (P5-TSK-008, INV-HIST-02)';
    END IF;
    IF NOT ((OLD.status = 'AUTH_DISPATCHED' AND NEW.status IN ('AUTH_UNKNOWN', 'AUTHORIZED', 'FAILED'))
            OR (OLD.status = 'AUTH_UNKNOWN' AND NEW.status IN ('AUTHORIZED', 'FAILED'))
            OR (OLD.status = 'AUTHORIZED' AND NEW.status IN ('CAPTURE_DISPATCHED'))
            OR (OLD.status = 'CAPTURE_DISPATCHED' AND NEW.status IN ('CAPTURE_UNKNOWN', 'CAPTURED', 'FAILED'))
            OR (OLD.status = 'CAPTURE_UNKNOWN' AND NEW.status IN ('CAPTURED', 'FAILED'))) THEN
        RAISE EXCEPTION 'a payment attempt moves only along the machine''s edges (ADR-0045, INV-LIFE-02/-04)';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER payment_attempt_permits_only_machine_edges
    BEFORE UPDATE ON payments.payment_attempt
    FOR EACH ROW
    EXECUTE FUNCTION payments.payment_attempt_permits_only_machine_edges();

-- The append-only lifecycle history (the transfer_event ceremony).
CREATE TABLE payments.payment_attempt_event (
    id          bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    attempt_id  uuid        NOT NULL REFERENCES payments.payment_attempt (id),

    from_status text        NOT NULL
        CONSTRAINT payment_attempt_event_from_status_is_known
            CHECK (from_status IN ('AUTH_DISPATCHED', 'AUTH_UNKNOWN', 'AUTHORIZED', 'CAPTURE_DISPATCHED', 'CAPTURE_UNKNOWN', 'CAPTURED', 'FAILED')),
    to_status   text        NOT NULL
        CONSTRAINT payment_attempt_event_to_status_is_known
            CHECK (to_status IN ('AUTH_DISPATCHED', 'AUTH_UNKNOWN', 'AUTHORIZED', 'CAPTURE_DISPATCHED', 'CAPTURE_UNKNOWN', 'CAPTURED', 'FAILED')),

    actor_id    uuid        NOT NULL,
    occurred_at timestamptz NOT NULL
);

CREATE INDEX payment_attempt_event_by_attempt ON payments.payment_attempt_event (attempt_id);

COMMENT ON TABLE payments.payment_attempt IS
    'The provider-facing try (ADR-0045): every provider fact lives here - our per-operation idempotency references (INV-PAY-04), the provider''s references, the authorized and captured amounts, the mapped failure reason (INV-PAY-03). What Phase 8 reconciles on. Payloads arrive with transitions and never change once recorded.';
COMMENT ON COLUMN payments.payment_attempt.status IS
    'AUTH_DISPATCHED -> {AUTH_UNKNOWN, AUTHORIZED, FAILED}; AUTH_UNKNOWN -> {AUTHORIZED, FAILED}; AUTHORIZED -> CAPTURE_DISPATCHED; CAPTURE_DISPATCHED -> {CAPTURE_UNKNOWN, CAPTURED, FAILED}; CAPTURE_UNKNOWN -> {CAPTURED, FAILED}. CAPTURED is stable with no outgoing edge AND terminal (refunds reference it, never transition it); captured is not settled (INV-SET-01).';
COMMENT ON COLUMN payments.payment_attempt.auth_reference IS
    'The platform-minted idempotency reference the authorization was dispatched under (INV-PAY-04) - what the sweeper queries by. Exists from birth: the dispatch commits before the provider is asked (ADR-0046).';
COMMENT ON TABLE payments.payment_attempt_event IS
    'Append-only lifecycle history: the path an attempt took, as evidence rather than memory. Server-assigned order; SELECT and INSERT only.';

-- THE GRANTS ARRIVE WITH THE TABLE. SELECT and INSERT for the row's life; UPDATE is status
-- PLUS the payload columns the doors carry - wider than the intent's one column, and stated
-- as exactly this set by the aggregate's javadoc so the width is a reconciliation, not a
-- rediscovery. The birth facts (id, intent_id, auth_reference, created_at) stay unwritable.
-- No DELETE: an attempt's end is a status, never an absence.
GRANT SELECT, INSERT ON payments.payment_attempt TO finapp_app;
GRANT UPDATE (status, capture_reference, auth_provider_reference, capture_provider_reference, authorized_amount_minor, authorized_currency, authorized_scale, captured_amount_minor, captured_currency, captured_scale, failure_reason) ON payments.payment_attempt TO finapp_app;

GRANT SELECT, INSERT ON payments.payment_attempt_event TO finapp_app;
