-- The refund and its lifecycle history (P5-TSK-008, ADR-0045, ADR-0048).
--
-- A BOUNDED RETURN REFERENCING A CAPTURED ATTEMPT - its own aggregate, never an edge on the
-- intent or the attempt: refund totals are derived by views over these rows and stored
-- nowhere, which is what keeps SUCCEEDED and CAPTURED stable while refunds accumulate.
--
-- THE BOUND'S ARBITER, AND WHY IT IS AN ADVISORY LOCK IN A TRIGGER (the V009 pattern,
-- verbatim reasoning):
--   INV-PAY-05's refund half spans rows that do not exist yet: "this refund plus every prior
--   non-FAILED refund never exceeds the captured amount" is a sum over sibling rows, and two
--   concurrent refund INSERTs cannot see each other's uncommitted rows under READ COMMITTED -
--   a predicate in the INSERT's own statement re-evaluates against the statement snapshot and
--   both pass (the P2-TSK-015 write-skew shape). The command's lock-then-look on the attempt
--   row (P5-TSK-015) is the domain's half, but it binds only writers that run our code. So
--   the BEFORE INSERT trigger takes pg_advisory_xact_lock(3, hashtext(attempt_id)) -
--   namespace 3, registered in DISTRIBUTED_EXECUTION.md beside the relay's and V009's - and
--   sums committed non-FAILED siblings under it. Held to commit, for EVERY writer: two
--   refunds of one attempt serialize, and the loser re-judges what the winner committed.
--   Refunds of different attempts do not contend.
--
-- THE SAME TRIGGER CARRIES THE AGGREGATE'S CREATION RULES for the writer that never ran
-- Refund.create: only a CAPTURED attempt has anything to return, and the refund is in the
-- capture's currency and scale. A FAILED refund frees its budget (the sum counts non-FAILED
-- rows), which is correct in both directions: DISPATCHED and UNKNOWN rows hold budget - money
-- possibly moving - and only a provider refusal releases it.
--
-- The refusal is ERRCODE 23514 with a stable marker (payments_refund_is_bounded), translated
-- by the store when it arrives (P5-TSK-015) - the V007/V009 pattern. Messages name
-- identifiers and enumerated names, never an amount (INV-AUD-02).
--
-- EVERY GENERATED LIST BELOW HAS ONE DEFINITION: status CHECKs from RefundStatus.
-- sqlValueList(), the monetary shape from MoneyColumns.ColumnNames.ddl(), the reference
-- shapes from ProviderIdempotencyReference/ProviderReference, the reason bound from
-- Refund.MAX_REASON_LENGTH, the trigger edges from permittedTransitions().

CREATE TABLE payments.refund (
    -- UUIDv7, minted by the application (ADR-0013) - the value the refund posting is keyed by
    -- (payment-refund:<refundId>, ADR-0048).
    id                            uuid        PRIMARY KEY,

    -- Same schema, so the FK is legal and right.
    attempt_id                    uuid        NOT NULL REFERENCES payments.payment_attempt (id),

    -- The ADR-0003 three-column monetary shape, generated by MoneyColumns.ColumnNames.ddl().
    amount_minor BIGINT NOT NULL, currency CHAR(3) NOT NULL, scale SMALLINT NOT NULL, CHECK (currency ~ '^[A-Z]{3}$'), CHECK (scale BETWEEN 0 AND 9),

    -- A refund of nothing asserts nothing; a negative refund is a charge wearing a refund's
    -- clothes (the aggregate's constructor invariant).
    CONSTRAINT refund_amount_is_positive
        CHECK (amount_minor > 0),

    -- Required - refund creation is a privileged act and the reason is part of the act
    -- (PHASE_5_PLAN.md sections 8/11). Non-blank, and bounded by Refund.MAX_REASON_LENGTH
    -- (the Transfer.MAX_REFERENCE_LENGTH pattern: one definition, restated at the surface).
    reason                        text        NOT NULL
        CONSTRAINT refund_reason_is_bounded
            CHECK (length(reason) <= 200),
    CONSTRAINT refund_reason_is_not_blank
        CHECK (btrim(reason) <> ''),

    -- The Phase 3 hold the dispatch placed on the customer wallet (ledger.hold by value, no
    -- cross-schema FK - ADR-0029): the funds being returned must not be spent mid-flight;
    -- completion releases-and-posts atomically, failure releases with nothing posted
    -- (P5-TSK-015).
    hold_reference                uuid        NOT NULL,

    -- Our idempotency reference, minted at dispatch (INV-PAY-04); shape from
    -- ProviderIdempotencyReference. UNIQUE: one operation per reference.
    provider_idempotency_reference text       NOT NULL UNIQUE
        CONSTRAINT refund_idempotency_reference_shape
            CHECK (provider_idempotency_reference ~ '^[A-Za-z0-9-]{1,64}$'),

    -- The provider's refund reference - the completion's fact, and what Phase 8 reconciles.
    -- Shape from ProviderReference; plain UNIQUE (one provider in Phase 5, the V003 note).
    provider_reference            text        UNIQUE
        CONSTRAINT refund_provider_reference_shape
            CHECK (provider_reference ~ '^[A-Za-z0-9_.:-]{1,128}$'),

    -- Generated from RefundStatus.sqlValueList().
    status                        text        NOT NULL
        CONSTRAINT refund_status_is_known
            CHECK (status IN ('DISPATCHED', 'UNKNOWN', 'COMPLETED', 'FAILED')),

    -- Application-supplied from the injected Clock, never DEFAULT now().
    created_at                    timestamptz NOT NULL,

    -- The provider's reference exactly when COMPLETED, both directions (the aggregate's
    -- rule): a COMPLETED refund that cannot name the provider's refund is not evidence Phase
    -- 8 can reconcile, and a reference on a live row is an outcome nobody committed.
    CONSTRAINT refund_reference_arrives_exactly_when_completed
        CHECK ((status = 'COMPLETED') = (provider_reference IS NOT NULL))
);

-- The bound's read, and the view's ("this attempt's refunds").
CREATE INDEX refund_by_attempt ON payments.refund (attempt_id);

-- INV-PAY-05's refund half at DB-CONSTRAINT rank, for EVERY writer (see the header for why
-- this is an advisory lock in a trigger). Also the aggregate's creation preconditions: a
-- CAPTURED attempt, the capture's currency and scale.
CREATE OR REPLACE FUNCTION payments.refund_is_bounded_by_the_capture()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
DECLARE
    attempt_status   text;
    captured_minor   bigint;
    captured_ccy     char(3);
    captured_sc      smallint;
    refunded_total   bigint;
BEGIN
    -- The serializer: every writer refunding this attempt queues here, and a resumed loser's
    -- reads below see what the winner committed. Namespace 3 (DISTRIBUTED_EXECUTION.md).
    PERFORM pg_advisory_xact_lock(3, hashtext(NEW.attempt_id::text));

    SELECT status, captured_amount_minor, captured_currency, captured_scale
        INTO attempt_status, captured_minor, captured_ccy, captured_sc
        FROM payments.payment_attempt
        WHERE id = NEW.attempt_id;

    IF attempt_status IS NULL THEN
        RAISE EXCEPTION 'payments_refund_is_bounded: refund % references attempt %, which does not exist (INV-PAY-05)',
                NEW.id, NEW.attempt_id
            USING ERRCODE = '23514';
    END IF;
    IF attempt_status <> 'CAPTURED' THEN
        RAISE EXCEPTION 'payments_refund_is_bounded: refund % references attempt % in %, and only a CAPTURED attempt has anything to return (INV-PAY-05)',
                NEW.id, NEW.attempt_id, attempt_status
            USING ERRCODE = '23514';
    END IF;
    IF NEW.currency <> captured_ccy OR NEW.scale <> captured_sc THEN
        RAISE EXCEPTION 'payments_refund_is_bounded: refund % is not in attempt %''s captured currency and scale (INV-PAY-05, INV-MON-03)',
                NEW.id, NEW.attempt_id
            USING ERRCODE = '23514';
    END IF;

    SELECT coalesce(sum(sibling.amount_minor), 0)
        INTO refunded_total
        FROM payments.refund sibling
        WHERE sibling.attempt_id = NEW.attempt_id
          AND sibling.status <> 'FAILED';

    IF refunded_total + NEW.amount_minor > captured_minor THEN
        RAISE EXCEPTION 'payments_refund_is_bounded: refund % would take attempt %''s refunded sum past its captured amount (INV-PAY-05)',
                NEW.id, NEW.attempt_id
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER refund_is_bounded_by_the_capture
    BEFORE INSERT ON payments.refund
    FOR EACH ROW
    EXECUTE FUNCTION payments.refund_is_bounded_by_the_capture();

-- The machine's edges and the freeze, for EVERY writer: everything but status and the
-- provider's reference is immutable, the reference moves only from NULL to a value (arriving
-- with COMPLETED, the table CHECK holding the pairing), and a status move must be one of the
-- machine's own edges, generated from permittedTransitions(). Amounts frozen means the bound
-- above never needs re-judging on UPDATE.
CREATE OR REPLACE FUNCTION payments.refund_permits_only_machine_edges()
    RETURNS trigger
    LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.id <> NEW.id
        OR OLD.attempt_id <> NEW.attempt_id
        OR OLD.amount_minor <> NEW.amount_minor
        OR OLD.currency <> NEW.currency
        OR OLD.scale <> NEW.scale
        OR OLD.reason <> NEW.reason
        OR OLD.hold_reference <> NEW.hold_reference
        OR OLD.provider_idempotency_reference <> NEW.provider_idempotency_reference
        OR OLD.created_at <> NEW.created_at THEN
        RAISE EXCEPTION 'a refund''s record is immutable outside its outcome: the privileged act is what stays recorded (P5-TSK-008, INV-HIST-01)';
    END IF;
    IF OLD.provider_reference IS NOT NULL
        AND NEW.provider_reference IS DISTINCT FROM OLD.provider_reference THEN
        RAISE EXCEPTION 'a recorded provider fact never changes: the refund''s provider reference moves only from NULL to a value (INV-HIST-02)';
    END IF;
    IF NOT ((OLD.status = 'DISPATCHED' AND NEW.status IN ('UNKNOWN', 'COMPLETED', 'FAILED'))
            OR (OLD.status = 'UNKNOWN' AND NEW.status IN ('COMPLETED', 'FAILED'))) THEN
        RAISE EXCEPTION 'a refund moves only along the machine''s edges: DISPATCHED -> {UNKNOWN, COMPLETED, FAILED}, UNKNOWN -> {COMPLETED, FAILED} (ADR-0045, INV-LIFE-02/-04)';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER refund_permits_only_machine_edges
    BEFORE UPDATE ON payments.refund
    FOR EACH ROW
    EXECUTE FUNCTION payments.refund_permits_only_machine_edges();

-- The append-only lifecycle history (the transfer_event ceremony).
CREATE TABLE payments.refund_event (
    id          bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    refund_id   uuid        NOT NULL REFERENCES payments.refund (id),

    from_status text        NOT NULL
        CONSTRAINT refund_event_from_status_is_known
            CHECK (from_status IN ('DISPATCHED', 'UNKNOWN', 'COMPLETED', 'FAILED')),
    to_status   text        NOT NULL
        CONSTRAINT refund_event_to_status_is_known
            CHECK (to_status IN ('DISPATCHED', 'UNKNOWN', 'COMPLETED', 'FAILED')),

    actor_id    uuid        NOT NULL,
    occurred_at timestamptz NOT NULL
);

CREATE INDEX refund_event_by_refund ON payments.refund_event (refund_id);

COMMENT ON TABLE payments.refund IS
    'A bounded return referencing a CAPTURED attempt (ADR-0045): the sum of non-FAILED refunds never exceeds the captured amount, judged in the BEFORE INSERT trigger under advisory-lock namespace 3 for every writer (INV-PAY-05). Refund totals are derived from these rows and stored nowhere.';
COMMENT ON COLUMN payments.refund.hold_reference IS
    'ledger.hold.id by value; no cross-schema FK by design (ADR-0029). The dispatch places the hold; completion releases-and-posts atomically, failure releases with nothing posted (P5-TSK-015).';
COMMENT ON COLUMN payments.refund.status IS
    'DISPATCHED -> {UNKNOWN, COMPLETED, FAILED}; UNKNOWN -> {COMPLETED, FAILED}. Born DISPATCHED - the dispatch and its hold commit before the provider is asked (ADR-0046).';
COMMENT ON TABLE payments.refund_event IS
    'Append-only lifecycle history: the path a refund took, as evidence rather than memory. Server-assigned order; SELECT and INSERT only.';

-- THE GRANTS ARRIVE WITH THE TABLE. SELECT and INSERT for the row's life; UPDATE narrowed to
-- the outcome pair - status and the provider's reference. No DELETE: a refund's end is a
-- status, never an absence.
GRANT SELECT, INSERT ON payments.refund TO finapp_app;
GRANT UPDATE (status, provider_reference) ON payments.refund TO finapp_app;

GRANT SELECT, INSERT ON payments.refund_event TO finapp_app;
